services:
  chainlink:
    build: .
    container_name: trust-api-chainlink-node
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - 6688:6688
    volumes:
      - chainlink-data:/chainlink

  postgres:
    image: postgres:16.3
    container_name: trust-api-chainlink-node-db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  chainlink-data:
  postgres-data: